name: Deploy to Artifact Registry

on:
  push:
    branches: [ develop ]

env: 
  DATABASE_URL: '${{ secrets.DATABASE_URL }}'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPO_NAME }}/${{ secrets.IMAGE_NAME }} .
        docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPO_NAME }}/${{ secrets.IMAGE_NAME }}
    
    - name: Check for model changes
      id: model_change_check
      run: |
        git fetch origin ${{ github.event.before }}
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "Changed files:"
        echo "$CHANGED_FILES"

        if echo "$CHANGED_FILES" | grep -q 'app/api/domain/.*/models.py'; then
          echo "model_changed=true" >> $GITHUB_OUTPUT
        else
          echo "model_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Alembic revision
      env:
        DB_URL: ${{ secrets.DB_URL }}
        MODEL_CHANGED: ${{ steps.model_change_check.outputs.model_changed }}
      run: |
        pip install -r requirements.txt
        cd app
        mkdir -p alembic/versions
        if [ "$MODEL_CHANGED" = "true" ]; then
          alembic revision --autogenerate -m "Auto revision"
        else
          echo "No model changes, skipping revision"
        fi
    
    - name: Run Alembic Migration
      env:
        DB_URL: ${{ secrets.DB_URL }}
      run: |
        cd app
        alembic upgrade head

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy nyanco \
        --image=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPO_NAME }}/nyanco \
        --region=asia-northeast3 \
        --platform=managed \
        --allow-unauthenticated \
        --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }}

